apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-default
  namespace: default
spec:
  limits:
  - default: # this section defines default limits
      memory: 1Gi
    defaultRequest: # this section defines default requests
      cpu: 10m
      memory: 200Mi
    type: Container
