---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: secured
spec:
  chain:
    middlewares:
      - name: hsts-header
      - name: redirect-https
      - name: test-ratelimit
      - name: redirect-www
